-- MySQL Script generated by MySQL Workbench
-- Dom 16 Out 2016 17:40:16 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `codigo` DECIMAL NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INSS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSS` (
  `codigo` DECIMAL NOT NULL,
  `limiteSuperior` DOUBLE NOT NULL,
  `aliquota` DOUBLE NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IRRF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IRRF` (
  `codigo` DECIMAL NOT NULL,
  `limiteSuperior` DOUBLE NOT NULL,
  `aliquota` DOUBLE NULL,
  `desconto` DOUBLE NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profissao` (
  `codigo` DECIMAL NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `salarioBase` DOUBLE NOT NULL,
  `Disciplina_codigo` DECIMAL NULL,
  `INSS_codigo` DECIMAL NOT NULL,
  `IRRF_codigo` DECIMAL NOT NULL,
  PRIMARY KEY (`codigo`, `INSS_codigo`, `IRRF_codigo`),
  INDEX `fk_Profissao_Disciplina1_idx` (`Disciplina_codigo` ASC),
  INDEX `fk_Profissao_INSS1_idx` (`INSS_codigo` ASC),
  INDEX `fk_Profissao_IRRF1_idx` (`IRRF_codigo` ASC),
  CONSTRAINT `fk_Profissao_Disciplina1`
    FOREIGN KEY (`Disciplina_codigo`)
    REFERENCES `mydb`.`Disciplina` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profissao_INSS1`
    FOREIGN KEY (`INSS_codigo`)
    REFERENCES `mydb`.`INSS` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profissao_IRRF1`
    FOREIGN KEY (`IRRF_codigo`)
    REFERENCES `mydb`.`IRRF` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `matricula` DECIMAL(8) NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `telefone` DECIMAL(13) NULL,
  `email` VARCHAR(100) NULL,
  `dataAdmissao` DATE NULL,
  `valeTransporte_Dia` DECIMAL NULL,
  `Profissao_codigo` DECIMAL NOT NULL,
  `Profissao_INSS_codigo` DECIMAL NOT NULL,
  `Profissao_IRRF_codigo` DECIMAL NOT NULL,
  PRIMARY KEY (`matricula`, `Profissao_codigo`, `Profissao_INSS_codigo`, `Profissao_IRRF_codigo`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_Funcionario_Profissao1_idx` (`Profissao_codigo` ASC, `Profissao_INSS_codigo` ASC, `Profissao_IRRF_codigo` ASC),
  CONSTRAINT `fk_Funcionario_Profissao1`
    FOREIGN KEY (`Profissao_codigo` , `Profissao_INSS_codigo` , `Profissao_IRRF_codigo`)
    REFERENCES `mydb`.`Profissao` (`codigo` , `INSS_codigo` , `IRRF_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ferias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ferias` (
  `mesReferencia` DATE NOT NULL,
  `anoReferencia` DATE NOT NULL,
  `Funcionario_matricula` DECIMAL(8) NOT NULL,
  PRIMARY KEY (`mesReferencia`, `anoReferencia`, `Funcionario_matricula`),
  INDEX `fk_Ferias_Funcionario_idx` (`Funcionario_matricula` ASC),
  CONSTRAINT `fk_Ferias_Funcionario`
    FOREIGN KEY (`Funcionario_matricula`)
    REFERENCES `mydb`.`Funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DecimoTerceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DecimoTerceiro` (
  `requisicao` TINYINT(1) NOT NULL,
  `parcelaAcumulada` DOUBLE NOT NULL,
  `parcelaContador` SMALLINT(6) NULL,
  `Funcionario_matricula` DECIMAL(8) NOT NULL,
  PRIMARY KEY (`requisicao`, `parcelaAcumulada`, `Funcionario_matricula`),
  INDEX `fk_DecimoTerceiro_Funcionario1_idx` (`Funcionario_matricula` ASC),
  CONSTRAINT `fk_DecimoTerceiro_Funcionario1`
    FOREIGN KEY (`Funcionario_matricula`)
    REFERENCES `mydb`.`Funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Holerite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Holerite` (
  `mesReferencia` DATE NOT NULL,
  `anoReferencia` DATE NOT NULL,
  `salarioLiquido` DOUBLE NOT NULL,
  `faltas` BIGINT(20) NULL,
  `Funcionario_matricula` DECIMAL(8) NOT NULL,
  PRIMARY KEY (`mesReferencia`, `anoReferencia`, `salarioLiquido`, `Funcionario_matricula`),
  INDEX `fk_Holerite_Funcionario1_idx` (`Funcionario_matricula` ASC),
  CONSTRAINT `fk_Holerite_Funcionario1`
    FOREIGN KEY (`Funcionario_matricula`)
    REFERENCES `mydb`.`Funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
