#ifndef BASICO_ERROS_H
    #define BASICO_ERROS_H

    enum erros {
        E_ABRIR_ARQUIVO,
        E_ALOCAR_CLASS,
        E_ALOCAR_TAB_SIMB,
        E_ALOCAR_UTF8,
        E_ALOCAR_TAB_CAMPOS,
        E_ALOCAR_ATTR_CAMPOS,
        E_ALOCAR_INFO_ATTR_CAMPOS,
        E_ALOCAR_TAB_METODOS,
        E_ALOCAR_ATTR_METODOS,
        E_ALOCAR_INFO_ATTR_METODOS,
        E_ALOCAR_COD_METODOS,
        E_ALOCAR_EXC_COD_METODOS,
        E_ALOCAR_ATTR_COD_METODOS,
        E_ALOCAR_LIN_NMB_ATTR_COD_METODOS,
        E_ALOCAR_TAB_ATRIBUTOS
    };

#endif
